export const SUPPORTED_MODEL_IDS = Object.freeze([
  'claude-sonnet-5',
  'claude-opus-5',
  'claude-opus-4.8',
  'claude-opus-4.7',
  'claude-haiku-4.5',
  'gpt-5.6-sol',
  'gpt-5.6-sol-fast',
  'gpt-5.6-terra',
  'gpt-5.6-luna',
  'gpt-5.5',
  'gpt-5.4',
  'gpt-5.4-mini',
  'gpt-5.3-codex',
  'gpt-5-mini',
  'mai-code-1.1-flash',
  'gemini-3.8-flash',
  'gemini-3.7-flash',
  'gemini-3.6-flash',
  'gemini-3.5-flash',
  'grok-4.5',
  'gpt-6-sol',
  'gpt-6-astra',
  'grok-4.6',
]);

export const SUPPORTED_MODELS = new Set(SUPPORTED_MODEL_IDS);
export const SUPPORTED_EFFORT_VALUES = Object.freeze([
  'none',
  'minimal',
  'low',
  'medium',
  'high',
  'xhigh',
  'max',
]);
export const SUPPORTED_EFFORTS = new Set(SUPPORTED_EFFORT_VALUES);
export const SUPPORTED_CONTEXT_VALUES = Object.freeze(['default', 'long_context']);
export const SUPPORTED_CONTEXTS = new Set(SUPPORTED_CONTEXT_VALUES);

export const LUNA_LOW_DEFAULT_PROFILE = Object.freeze({
  model: 'gpt-5.6-luna',
  effort: 'low',
  context: 'default',
});

export const LUNA_MEDIUM_DEFAULT_PROFILE = Object.freeze({
  model: 'gpt-5.6-luna',
  effort: 'medium',
  context: 'default',
});

export const SOL_MAX_DEFAULT_SOURCE_PROFILE = Object.freeze({
  model: 'gpt-6-sol',
  effort: 'max',
  context: 'default',
});

export const EVIDENCE_CURATOR_PROFILE = Object.freeze({
  model: 'gpt-5.4-mini',
  effort: 'low',
  context: 'default',
});

export const AUTOMATIC_ROUTE_ROLE_CATALOG = Object.freeze({
  'history-reader': Object.freeze({
    role: 'history-reader',
    dispatchKind: 'task',
    profile: LUNA_LOW_DEFAULT_PROFILE,
    agentTypes: ['general-purpose'],
    toolCategories: ['history-sql'],
    toolNames: ['session_store_sql'],
    description: 'Bounded session history lookup and compact summary',
  }),
  'history-auditor': Object.freeze({
    role: 'history-auditor',
    dispatchKind: 'task',
    profile: LUNA_MEDIUM_DEFAULT_PROFILE,
    agentTypes: ['general-purpose'],
    toolCategories: ['history-sql'],
    toolNames: ['session_store_sql'],
    description: 'Cross-session routing, policy, and cost audit',
  }),
  'host-diagnostics-reader': Object.freeze({
    role: 'host-diagnostics-reader',
    dispatchKind: 'task',
    profile: LUNA_LOW_DEFAULT_PROFILE,
    agentTypes: ['general-purpose'],
    toolCategories: ['shell'],
    toolNames: ['bash'],
    description: 'Read-only host memory, swap, PSI, and process diagnostics',
  }),
  'repository-reader': Object.freeze({
    role: 'repository-reader',
    dispatchKind: 'task',
    profile: LUNA_LOW_DEFAULT_PROFILE,
    agentTypes: ['explore', 'general-purpose'],
    toolCategories: ['repository-read', 'repository-search'],
    toolNames: ['view', 'rg', 'glob'],
    description: 'Exact bounded repository reading and search',
  }),
  'external-evidence-reader': Object.freeze({
    role: 'external-evidence-reader',
    dispatchKind: 'task',
    profile: LUNA_LOW_DEFAULT_PROFILE,
    agentTypes: ['general-purpose'],
    toolCategories: ['web', 'github', 'browser', 'mcp'],
    toolNames: [
      'web_fetch',
      'web_search',
      'get_file_contents',
      'search_code',
      'search_users',
      'get_copilot_space',
      'list_copilot_spaces',
      'browser_navigate',
      'browser_navigate_back',
      'browser_wait_for',
      'browser_snapshot',
      'browser_console_messages',
      'browser_network_request',
      'browser_network_requests',
      'browser_take_screenshot',
      'browser_find',
      'browser_tabs',
      'browser_close',
    ],
    toolNamePrefixes: [
      'ha_get_',
      'ha_config_get_',
      'ha_list_',
      'ha_search',
      'plex-get_',
      'plex-search_',
      'get_',
      'list_',
      'search_',
      'arr_search_',
      'arr_status',
      'fetch',
    ],
    description: 'Read-only web, GitHub, browser, and MCP evidence retrieval',
  }),
  'evidence-curator': Object.freeze({
    role: 'evidence-curator',
    dispatchKind: 'task',
    profile: EVIDENCE_CURATOR_PROFILE,
    agentTypes: ['general-purpose'],
    toolCategories: ['repository-read', 'repository-search', 'history-sql', 'web', 'github', 'browser', 'mcp'],
    toolNames: [
      'view',
      'rg',
      'glob',
      'session_store_sql',
      'web_fetch',
      'web_search',
      'get_file_contents',
      'search_code',
      'search_users',
      'get_copilot_space',
      'list_copilot_spaces',
      'browser_navigate',
      'browser_navigate_back',
      'browser_wait_for',
      'browser_snapshot',
      'browser_console_messages',
      'browser_network_request',
      'browser_network_requests',
      'browser_take_screenshot',
      'browser_find',
      'browser_tabs',
      'browser_close',
    ],
    toolNamePrefixes: [
      'ha_get_',
      'ha_config_get_',
      'ha_list_',
      'ha_search',
      'plex-get_',
      'plex-search_',
      'get_',
      'list_',
      'search_',
      'arr_search_',
      'arr_status',
      'fetch',
    ],
    description: 'Explicit tandem evidence preparation using exact readers only',
  }),
  'cli-doc-reader': Object.freeze({
    role: 'cli-doc-reader',
    dispatchKind: 'deterministic',
    toolName: 'fetch_copilot_cli_documentation',
    profile: null,
    agentTypes: [],
    toolCategories: ['documentation'],
    toolNames: ['fetch_copilot_cli_documentation'],
    description: 'Deterministic Copilot CLI documentation lookup',
  }),
});

export const AUTOMATIC_ROUTE_ROLE_IDS = Object.freeze(
  Object.keys(AUTOMATIC_ROUTE_ROLE_CATALOG),
);
